### PR TITLE
Release 1.2.0

### LINKED ISSUE #11: Rate Limiting
I've seen errors saying I'm probably rate limited, after research I've found that normally up to 10,000 API requests can be made per day if you have your API key - I have 1,200 games.

Maybe wait a few seconds if there is an error?

### LINKED ISSUE #41: KeyError: 'Valve' on execution.
```
└─>➜⊃━☆ﾟ.*･｡ﾟ ❯  python3 ProtonDB-Tags.py --check-native
Steam found at: /home/pm/.local/share/Steam/userdata
Found user 0: anonymous   (Could not load username from Steam)
Found user 1: 150966242   PoorPocketsMcNewHold
Which user number would you like to open? 1
Selected: 
Traceback (most recent call last):
  File "/home/pm/ProtonDB-Tags/ProtonDB-Tags.py", line 335, in <module>
    main(ARGUMENTS)
  File "/home/pm/ProtonDB-Tags/ProtonDB-Tags.py", line 243, in main
    apps = sharedconfig[configstore]["Software"]["Valve"]["Steam"][get_apps_key(sharedconfig, configstore)]
KeyError: 'Valve'
```
Currently, at launch, the ProtonDB-Tags script is creating this perpetual error when launching it, either with or without the check-native argument.
I do note that I don't have any other accounts logged into Steam.
[sharedconfig.vdf.txt](https://github.com/CorruptComputer/ProtonDB-Tags/files/7112201/sharedconfig.vdf.txt)

### LINKED ISSUE #42: Getting various Python Errors when Running
Traceback (most recent call last):
  File "/home/domglusk/gitcloned/ProtonDB-Tags/ProtonDB-Tags.py", line 8, in <module>
    import vdf
  File "/home/domglusk/.local/lib/python3.10/site-packages/vdf/__init__.py", line 19, in <module>
    from vdf.vdict import VDFDict
  File "/home/domglusk/.local/lib/python3.10/site-packages/vdf/vdict.py", line 9, in <module>
    class _kView(_c.KeysView):
AttributeError: module 'collections' has no attribute 'KeysView'

These are the errors. The requirements are met, that was confirmed by the requirements command. Don't know if its an Arch thing or what. Any possible solution? This is from the github version NOT the aur version (as the aur version also gives an error)

### PR DESCRIPTION
**Pull request by CorruptComputer**
Changes:
- Improved caching logic, fixes #11
  - Both the Steam Native status and ProtonDB rating are cached for a minimum of 7 days + a random offset between 1 and 7 days per game.
  - This random offset should help speed up the scan times if you run this script multiple times per week and reduce the load caused on those services by this existing.
  - Current caches will be incompatible, however the script should handle these nicely so those old values won't be sitting around.
  - The cache can be bypassed by adding `--skip-cache` as a command-line flag. This will still add the value to your local cache, but will just skip reading it and force fresh data to be retrieved.
- Option to read games list from Steam API
  - The first time you try it, this will ask you for your Steam API key and Steam ID.
    - These values can be cleared from the config by adding the `--clear-config` argument.
  - Both of these will only be stored locally, and will only be used to contact the Steam API.
    - This config will be located in one of these two locations, depending on if you have `$XDG_CONFIG_HOME` set.
      - `$XDG_CONFIG_HOME/ProtonDB-Tags/config.json`
      - `$HOME/.config/ProtonDB-Tags/config.json`
  - **Be warned that using this option will most likely clear the current tags from some of your games, and should only be used as a work-around if games aren't showing up for you.**
  - This can be used by adding `--fetch-games` or `-f` as a command-line flag.
- Fixes #41
- Fixes #42
- Swap broken TravisCI tests with GitHub Actions tests.
- Remove some skipped pylint checks, as these issues have been fixed.
- Update README.md and add issue templates.

### CODE REVIEW

**Comment by CorruptComputer** [comment]
Bruh what do you mean there are merge conflicts? Nothing should have changed with the `main` branch...? Need to figure out what is going on with that.

**Comment by CorruptComputer** [comment]
This should be pretty much done now, I think I've done all the testing that I would need to be comfortable releasing this. Going to leave this PR open for a day in case anyone would like to review or give any feedback on this.

**Comment by PoorPocketsMcNewHold** [comment]
Tested it. Crashed a couple of times on me to to a time out request to protondb.

```
Traceback (most recent call last):
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib64/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib64/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pm/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.protondb.com', port=443): Max retries exceeded with url: /api/v1/reports/summaries/215350.json (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pm/Documents/ProtonDB-Tags/ProtonDB-Tags.py", line 337, in <module>
    main(ARGUMENTS)
  File "/home/pm/Documents/ProtonDB-Tags/ProtonDB-Tags.py", line 229, in main
    protondb_rating = get_protondb_rating(app_id, args.skip_cache)
  File "/home/pm/Documents/ProtonDB-Tags/ProtonDB-Tags.py", line 153, in get_protondb_rating
    protondb_api_result = requests.get(api_url)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.protondb.com', port=443): Max retries exceeded with url: /api/v1/reports/summaries/215350.json (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))
```
as well as pure timeout ones too.

```
Traceback (most recent call last):
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib64/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pm/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pm/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib64/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pm/Documents/ProtonDB-Tags/ProtonDB-Tags.py", line 337, in <module>
    main(ARGUMENTS)
  File "/home/pm/Documents/ProtonDB-Tags/ProtonDB-Tags.py", line 229, in main
    protondb_rating = get_protondb_rating(app_id, args.skip_cache)
  File "/home/pm/Documents/ProtonDB-Tags/ProtonDB-Tags.py", line 153, in get_protondb_rating
    protondb_api_result = requests.get(api_url)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/pm/.local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
but other than that. Works fine. 
image

**Comment by CorruptComputer** [comment]
@PoorPocketsMcNewHold Thanks for reporting those! I've improved the error handling around those requests, so these errors should be taken care of now.

Going to go ahead and release this now, for completeness as well I'll just go ahead and attach a sample output of this new version of the script:
```
[ngupton@andromeda ProtonDB-Tags]$ ProtonDB-Tags.py --check-native --fetch-games
Steam found at: /home/ngupton/.local/share/Steam/userdata
Found user 0: 85729560   CorruptComputer
Only one user found.
Selected: /home/ngupton/.local/share/Steam/userdata/85729560/7/remote/sharedconfig.vdf

Existing config not found.
Config will be created here: /home/ngupton/.config/ProtonDB-Tags/config.json

Due to recent changes in Steam, it has become more difficult to get an accurate list of the games in your library.
In order to work around this, we can use the Steam API to get this information directly.
Please go here to generate an API key: https://steamcommunity.com/dev/apikey

This API key will be saved in the config for ProtonDB-Tags on your PC.
Api key (not shown): 

Please go here to find your steamID64 (should look similar to 76561197960287930): https://www.steamidfinder.com
steamID64: 76561198045995288
Found 902 new games from the Steam API.

Steam native cache not found.
This will be created here: /home/ngupton/.cache/ProtonDB-Tags/steamNativeCache.json

ProtonDB cache not found.
This will be created here: /home/ngupton/.cache/ProtonDB-Tags/protonDBCache.json

Found a total of 902 Steam games.
92 | platinum (1 of 902)
211 | unrated (2 of 902)
440 | native (3 of 902)
570 | native (4 of 902)
...
```

**Pull request merged**
